### ISSUE TITLE
Outdated GitHub Action

### ISSUE THREAD

**Issue by jeffpaul** [thrivedesk/wp-thrivedesk#22]
Note that https://github.com/thrivedesk/wp-thrivedesk/blob/655d12f6b6563b04bbff5c24db09567a5b77d3ef/.github/workflows/push-asset-readme-update.yml#L13 is using an outdated action and should update to use https://github.com/10up/action-wordpress-plugin-asset-update

**Comment by Rijoanul-Shanto** [comment]
Thanks for pointing that out! @jeffpaul 

Appreciate your help.

**Comment by alaminfirdows** [comment]
https://github.com/thrivedesk/wp-thrivedesk/pull/30
